version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET= 
      - JWT_EXPIRATION=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET= 
      - GOOGLE_CALLBACK_URL= 
      - DB_HOST = 
      - DB_USER = 
      - DB_PASS =
      - DB_NAME =
      - SESSION_SECRET=
      - REDIS_URL=
    restart: always
    volumes:
      - .:/app
      - /app/node_module
    command: ["npm", "start"] # Use nodemon for auto-restart
